### ISSUE TITLE
Clean ABAP

### ISSUE THREAD

**Issue by tobiashofmann** [tobiashofmann/sap-dev-tech-radar#14]
Commit: 97110a088266f9639aa621ed23a9b7d578fe4824

**Comment by larshp** [comment]
description missing update, https://github.com/tobiashofmann/sap-dev-tech-radar/blob/proposals-2024.06/definitions/frameworks/cleanabap.toml

**Comment by tobiashofmann** [comment]
Updated description: f0f63c16e16af6d5247caea77a0dc9d20c502876

**Comment by tobiashofmann** [comment]
Added in SDTR 2024.6
