### ISSUE TITLE
CVA

### ISSUE THREAD

**Issue by tobiashofmann** [tobiashofmann/sap-dev-tech-radar#15]
Code Vulnerability Analyzer (CVA)
Commit: ed1c920b3c87a283d531899004d161984c1e4316

**Comment by larshp** [comment]
Rumors says the license for on-prem is 6 digits, its probably nice to have and all, but I doubt it will be adopted just due to pricing

**Comment by tobiashofmann** [comment]
I do not think that CVA will make it to the release of the SDTR. My guess is that the criteria of usage and adoption is just too low to make CVA relevant for the usual SAP developer. 

I added it here so the community can decide on this topic, and maybe someone from SAP can proof that it is relevant.

**Comment by tobiashofmann** [comment]
**Not** added in SDTR 2024.6
