### ISSUE TITLE
Is the text for #29 "Custom Fields and Logic" correct?

### ISSUE THREAD

**Issue by BaerbelW** [tobiashofmann/sap-dev-tech-radar#20]
The text shown for #29 at https://tobiashofmann.github.io/sap-dev-tech-radar/html/customfields.html looks to be a copy of what is shown for BOPF at #37 https://tobiashofmann.github.io/sap-dev-tech-radar/html/bopf.html

Is that intentional or accidental?

Btw, neat and helpful overview!

Cheers
Bärbel

**Comment by tobiashofmann** [comment]
You are right, the text wasn't correct. The item should now have to correct text for Custom Fields and Logics.
