### ISSUE TITLE
Voting 2024.6

### ISSUE THREAD

**Issue by tobiashofmann** [tobiashofmann/sap-dev-tech-radar#28]
Submitting new proposals for the 2024.6 version of the SAP development tech radar ended. The branch is set to read-only.

For voting, the branch [voting-2024.6](https://github.com/tobiashofmann/sap-dev-tech-radar/tree/voting-2024.6) is created.

The submitted propsals are:

- [ABAP Unit](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/5)
- [ABAP Test Cockpit](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/6)
- [MDK](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/7)
- [SEGW](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/8)
- [Kapsel](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/9)
- [BTP SDK for iOS](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/10)
- [BTP SDK for Android](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/11)
- [eCATT](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/12)
- [ABAP Cleaner](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/13)
- [Clean ABAP](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/14)
- [CVA](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/15)
- [WDI5](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/21)
- [SOAP](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/22)
- [SAP Gui](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/24)
- [Mobile Cards](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/25)
- [ui5 linter](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/26)
- [Flexible Programming Model FPM](https://github.com/tobiashofmann/sap-dev-tech-radar/issues/27)

by default all proposals are going to be added, if not voted otherwise.

**Comment by tobiashofmann** [comment]
**CVA**

I vote to take CVA out. Not enough customers, user base, experience available. Only time I see it mentioned is by SAP trying to sell it, not by customers or even partners.

**Comment by pokrakam** [comment]
How does voting work? Couldn't find any info on it.

**Comment by tobiashofmann** [comment]
@pokrakam provide your input here. Basically you state what you do not want to have included in the SDTR from the submitted proposals and give a justification.

**Comment by tobiashofmann** [comment]
Voting phase ended
